kind: feedfwd
task: class
network:
  input:
    size: 400
  hidden:
    size: [25]
    activation: sigmoid
  output:
    size: 10
    activation: softmax
training:
  kind: backprop
  cost: xentropy
  params:
    lambda: 1.0
  optimize:
    method: bfgs
    iterations: 69
