kind: feedfwd
task: class
network:
  input:
    size: 784
  hidden:
    size: [25, 20]
    activation: relu
  output:
    size: 10
    activation: softmax
training:
  kind: backprop
  cost: loglike
  params:
    lambda: 1.0
  optimize:
    method: bfgs
    iterations: 82
